version: "3.8"
services:
  django_dev:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: hic_server:v1
    environment:
      - PORT=8020
    env_file:
      - src/.env
    expose:
      - 8019
    volumes:
      - ./hic_data:/app/api/hic/hic_data
      - ./session:/app/api/hic/session
      - static_dev:/app/static/
    networks:
      - cellscope_network
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:15
    restart: always
    command: -p 5434
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - src/.env
    expose:
      - 5434
    ports:
      - "5434:5434"
    networks:
      - cellscope_network

  nginx_dev:
    image: nginx:latest
    ports:
      - "8020:80"
    depends_on:
      - django_dev
    volumes:
      - ./src/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_dev:/etc/nginx/html/static/
    networks:
      - cellscope_network
volumes:
  postgres_data:
  static_dev:


networks:
  cellscope_network:
    external: true
