# Generated by Django 3.2 on 2023-01-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dataset_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='cells',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='dataset',
            name='resolutions',
            field=models.TextField(default='500000'),
        ),
    ]
