# Generated by Django 4.1.2 on 2024-08-16 02:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_dataset_id_alter_dataset_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('file_path', models.TextField(default='')),
            ],
        ),
    ]
